### ISSUE TITLE
Deposited balance gets displayed incorrectly

### ISSUE THREAD

**Issue by mschneider** [solana-labs/oyster-lending#3]
I deposited 0.12 SRM using three transactions (2x0.01 & 1x0.1) but the Dashboard displays a deposit of 0.03. I was able to borrow 0.08 USDC using the 0.12 SRM as collateral.

![image](https://user-images.githubusercontent.com/144124/100515298-4eefaa00-317b-11eb-82d2-32905687826a.png)

You can find the deposit transactions here:
SRM account: https://explorer.solana.com/address/ECiJkya7SKnoPgVcDpJnSdSTrLj6KkEhrv52R8yPmfaj
slots: 51,959,948 - 51,960,387

**Comment by jstarry** [comment]
Thanks for the issue and playing with the demo protocol a bit :)

I think this was fixed here: https://github.com/solana-labs/oyster-lending/commit/26820015140eb62e079741aa09736de76d27b569

Can you double check if you have time?

**Comment by mschneider** [comment]
confirmed, it's working now 👍  i was able to withdraw the full amount
