### ISSUE TITLE
When borrowing, the token prices don't make sense, don't match

### ISSUE THREAD

**Issue by yamijuan** [solana-labs/oyster-lending#45]
@jstarry I found a weird behavior while using the borrow feature. If, for example, 1 SOL is $2 and 1 USDC is $1, when I borrow 1 USDC it charges me 1 SOL that is $2. 
![image](https://user-images.githubusercontent.com/25460766/105607622-c6058100-5d6d-11eb-9d50-9c1d194f1934.png)

**Comment by jstarry** [comment]
@yamijuan did you figure out the issue?
